"""Promote locked cookbook graphs into the tracked cookbook/ tree.

    quality/authored/cookbook-<category>/<id>/v1.ptex  ->  cookbook/<category>/<id>.ptex

quality/authored/ is gitignored build output from the cookbook_*.py builders.
cookbook/ is the tracked, shipped copy the MCP server serves through
list_examples / load_example and that a person can open in Material Maker.

Usage (from the repo root):
  .venv\\Scripts\\python.exe -m quality.promote_cookbook                 # copy every category
  .venv\\Scripts\\python.exe -m quality.promote_cookbook cookbook-stone  # one label
  .venv\\Scripts\\python.exe -m quality.promote_cookbook --check         # diff, do not write

--check is the regression baseline: rebuild with the builders, then --check.
Any tracked file that is missing or differs from its authored v1.ptex is
reported and the exit code is 1. Run without --check to accept the new output.
"""
import json
import shutil
import sys
from pathlib import Path

from quality.naming import iter_nodes

_ROOT = Path(__file__).resolve().parent.parent
AUTHORED = _ROOT / "quality" / "authored"
COOKBOOK = _ROOT / "cookbook"
PREFIX = "cookbook-"

BEGIN, END = "<!-- nodes:begin -->", "<!-- nodes:end -->"


def node_table(graph: dict) -> str:
    """The generated card block: one row per checkable node, with the
    subgraph it lives in. Reserved nodes (Material, gen_*) are not rows."""
    rows = [f"| {label or '(top level)'} | {n['name']} | {n.get('type', '')} |"
            for label, n in iter_nodes(graph)]
    return "\n".join([
        BEGIN,
        "## Nodes",
        "",
        "Generated by `python -m quality.promote_cookbook` from the shipped graph;",
        "do not edit by hand. Open the `.ptex` and look for these names.",
        "",
        "| Subgraph | Node | Type |",
        "|---|---|---|",
        *rows,
        END,
    ]) + "\n"


def _split_block(text: str):
    """(before, block, after) or None when the markers are absent."""
    i, j = text.find(BEGIN), text.find(END)
    if i < 0 or j < 0 or j < i:
        return None
    j_end = j + len(END)
    if text[j_end:j_end + 1] == "\n":
        j_end += 1
    return text[:i], text[i:j_end], text[j_end:]


def write_card_block(card: Path, graph: dict) -> None:
    text = card.read_text(encoding="utf-8") if card.is_file() else ""
    block = node_table(graph)
    parts = _split_block(text)
    if parts is None:
        sep = "" if text.endswith("\n\n") else ("\n" if text.endswith("\n") else "\n\n")
        new = text + sep + block
    else:
        new = parts[0] + block + parts[2]
    card.write_text(new, encoding="utf-8", newline="\n")


def check_card_block(card: Path, graph: dict) -> str | None:
    if not card.is_file():
        return f"{card}: missing recipe card"
    parts = _split_block(card.read_text(encoding="utf-8"))
    if parts is None:
        return f"{card}: node table missing (run promote_cookbook.py to add it)"
    if parts[1] != node_table(graph):
        return f"{card}: node table stale (run promote_cookbook.py to refresh it)"
    return None


def promote(authored_root: Path, cookbook_root: Path, check: bool = False,
            labels: list[str] | None = None) -> list[str]:
    """Copy (or, with check=True, compare) every cookbook-*/<id>/v1.ptex.
    Returns a list of problem strings; empty means clean."""
    if not authored_root.is_dir():
        return [f"{authored_root}: not a directory (nothing to promote or check)"]
    problems: list[str] = []
    all_label_dirs = sorted(d for d in authored_root.glob(PREFIX + "*") if d.is_dir())
    label_dirs = all_label_dirs
    if labels:
        matched = {d.name for d in all_label_dirs}
        for label in labels:
            if label not in matched:
                problems.append(f"{label}: no such directory under {authored_root}")
        label_dirs = [d for d in all_label_dirs if d.name in labels]
    for label_dir in label_dirs:
        category = label_dir.name[len(PREFIX):]
        for case_dir in sorted(p for p in label_dir.iterdir() if p.is_dir()):
            src = case_dir / "v1.ptex"
            if not src.is_file():
                problems.append(f"{case_dir}: no v1.ptex to promote")
                continue
            dst = cookbook_root / category / f"{case_dir.name}.ptex"
            src_json = json.loads(src.read_text(encoding="utf-8"))
            card = cookbook_root / category / f"{case_dir.name}.md"
            if check:
                if not dst.is_file():
                    problems.append(f"{dst}: missing (run promote_cookbook.py to add it)")
                else:
                    dst_json = json.loads(dst.read_text(encoding="utf-8"))
                    if src_json != dst_json:
                        problems.append(f"{dst}: differs from {src}")
                card_problem = check_card_block(card, src_json)
                if card_problem:
                    problems.append(card_problem)
            else:
                dst.parent.mkdir(parents=True, exist_ok=True)
                shutil.copyfile(src, dst)
                write_card_block(card, src_json)
    return problems


def main(argv: list[str]) -> int:
    check = "--check" in argv
    labels = [a for a in argv if a != "--check"] or None
    problems = promote(AUTHORED, COOKBOOK, check=check, labels=labels)
    for p in problems:
        print(p)
    if problems:
        print(f"{len(problems)} problem(s)")
        return 1
    print("cookbook/ is " + ("in sync with quality/authored/" if check else "updated"))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
